### ISSUE TITLE
curve behavior

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/blackbody-spectrum#69] opened 2018-12-03 23:31 UTC
In Graphing Quadratics https://github.com/phetsims/graphing-quadratics/issues/117, @KatieWoe said:
> This is also recently seen in Blackbody spectrum, though the curve was generally less sharp so the effect is less noticeable.

And:
> @DianaTavares since you're the designer for blackbody-spectrum, what do you think? Do you want an issue for this?

**Comment by KatieWoe** [comment] 2018-12-03 23:32
Duplicate of https://github.com/phetsims/blackbody-spectrum/issues/68.  Closing with link to issue.

**Closed by KatieWoe** 2018-12-03 23:32 UTC
Labels: type:duplicate
