### ISSUE TITLE
Sim blacks out when spectral radiance is 0.0001 and blackbody temp is 11000K

### ISSUE THREAD

**Issue by megan-phet** [phetsims/blackbody-spectrum#63] opened 2018-11-10 01:04 UTC
<b>Test Device</b>
- MacBook Pro

<b>Operating System</b>
- MacOS 10.14

<b>Browser</b>
- Only on Safari

<b>Problem Description</b>

- For phetsims/QA#215

Screan blacks out when spectral radiance is at 0.0001 and blackbody temp is at 11000K.

<b>Steps to Reproduce</b>

1. Change the spectral radiance to 0.0001
2. Change the blackbody temp to the max

<b>Visuals</b>
![kapture 2018-11-09 at 17 35 31](https://user-images.githubusercontent.com/40698031/48295275-cc86d700-e447-11e8-9e99-bccb3a1a162f.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>
Name: ‪Blackbody Spectrum‬
URL: https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.12/phet/blackbody-spectrum_en_phet.html
Version: 1.0.0-dev.12 2018-11-02 23:46:56 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15
Language: en-US
Window: 1303x733
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 NVIDIA-12.0.19 355.11.10.50.10.103)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"cca8e36e","branch":"master"},"blackbody-spectrum":{"sha":"3db65ad6","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"fa2fbadf","branch":"master"},"dot":{"sha":"bbbd8526","branch":"master"},"joist":{"sha":"82521d0c","branch":"master"},"kite":{"sha":"380cef53","branch":"master"},"phet-core":{"sha":"1b90ac2f","branch":"master"},"phet-io":{"sha":"e230c094","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"246085c1","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"7479b0ec","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"c46f7839","branch":"master"},"phet-io-wrappers":{"sha":"ded21e3f","branch":"master"},"phetcommon":{"sha":"cd63d89a","branch":"master"},"query-string-machine":{"sha":"06ed6276","branch":"master"},"scenery":{"sha":"5013941c","branch":"master"},"scenery-phet":{"sha":"2286294f","branch":"master"},"sherpa":{"sha":"97e70540","branch":"master"},"sun":{"sha":"a423abfb","branch":"master"},"tambo":{"sha":"296cf3ba","branch":"master"},"tandem":{"sha":"1b93c58b","branch":"master"}}
</details>

**Comment by KatieWoe** [comment] 2018-11-12 20:28
@phet-steele It sounded like @megan-phet was having trouble adding assignments and tags for some reason.  I've been looking in to see what the cause might be, but haven't found anything yet.  Thanks for adding them.

**Comment by phet-steele** [comment] 2018-11-12 20:38
> Correction: It looks like she doesn't have write access in this repo because it's not listed in the QA group.

I see, thanks for finding that out! Sorry @megan-phet.

**Comment by KatieWoe** [comment] 2018-11-20 15:33
https://github.com/phetsims/blackbody-spectrum/issues/65 additional details in duplicate issue.  (I initially thought it was a new issue on iPads).

**Comment by KatieWoe** [comment] 2018-11-20 17:42
Significant lag also occurs.  This issue also seems to occur during the last few zoom ins (can occur at 0.00007, or at least large amounts of lag) and most of the high temperatures.

**Comment by KatieWoe** [comment] 2019-02-25 17:01
The blackout portion of this issue seems solved when testing Mac 10.14 safari in the new dev version. @arnabp

**Comment by arnabp** [comment] 2019-02-26 22:31
Since blackout issue appears to be fixed, I'm closing. I will note however, that general performance issues will continue to be observed and fixed on a general basis.

**Closed by arnabp** 2019-02-26 22:31 UTC
Labels: status:fixed-pending-testing, type:bug
