### ISSUE TITLE
Pointer Areas on Graph Value Arrows Stay After Arrows Leave

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#91] opened 2019-05-22 16:57 UTC
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/320
The pointer areas for the Graph Values, particularly the arrows that are there when first selected, behave oddly.  The arrows can be grabbed with a mouse, but once they are gone that area is not grabbable.  The red area that shows touch area does not leave.  That means that the area is always grabbable by touch.
**Steps to reproduce:**
1. showPointerAreas
2. Turn on Graph Values
3. Move the point
4. Observe pointer area

**Screenshots:**
![oddpointerartifact](https://user-images.githubusercontent.com/41024075/58193411-292d3f00-7c80-11e9-8a9c-c771ee8442d9.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Blackbody Spectrum‬
URL: https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.16/phet/blackbody-spectrum_en_phet.html?showPointerAreas
Version: 1.0.0-dev.16 2019-05-21 21:44:52 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment] 2019-05-22 17:21
yes, that looks strange. I am sure that the touch area should be big because is just a dot, but I don't think it should to be the same that the arrows when they are not any more in the play area.

**Comment by arnabp** [comment] 2019-05-28 21:12
@jbphet and I took a look at this. While the touch area does seem strange, the additional touch area doesn't seem to really hurt the functionality of the sim. There's no immediate overlap with anything that would prevent users from moving the point, and I tested overlap against the panel on the right and found no issues with functionality. It's not so big that it seems unreasonable for the point to be touchable at that range. Overall we don't really see this as being an issue.

Adding @ariel-phet on to this as well.

**Comment by ariel-phet** [comment] 2019-05-30 02:41
@KatieWoe thanks for pointing out. I confirmed this touch area does indeed exists on either side of the dot using my Win 10 touch screen (it is not just a quirk of `?showPointerAreas`)

However, I agree with the assessment above, it is not really causing any harm. And probably doesn't need to be fixed. Closing

**Closed by ariel-phet** 2019-05-30 02:41 UTC
Labels: type:bug
