### ISSUE TITLE
Assertion failed: y should be a finite number

### ISSUE THREAD

**Issue by phet-steele** [phetsims/blackbody-spectrum#23] opened 2018-04-09 15:14 UTC
```
Error: Assertion failed: y should be a finite number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1523228146488/assert/js/assert.js:22:13)
    at RichText.translate (https://bayes.colorado.edu/continuous-testing/snapshot-1523228146488/scenery/js/nodes/Node.js?bust=1523235106975:1792:19)
    at RichText.setBottom (https://bayes.colorado.edu/continuous-testing/snapshot-1523228146488/scenery/js/nodes/Node.js?bust=1523235106975:2494:12)
    at RichText.set bottom [as bottom] (https://bayes.colorado.edu/continuous-testing/snapshot-1523228146488/scenery/js/nodes/Node.js?bust=1523235106975:2497:32)
    at updateGraph (https://bayes.colorado.edu/continuous-testing/snapshot-1523228146488/blackbody-spectrum/js/blackbody-spectrum/view/GraphDrawingNode.js?bust=1523235106975:152:32)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1523228146488/blackbody-spectrum/js/blackbody-spectrum/view/GraphDrawingNode.js?bust=1523235106975:269:7)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1523228146488/axon/js/Emitter.js?bust=1523235106975:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1523228146488/axon/js/Property.js?bust=1523235106975:282:29)
    at NumberProperty._setAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1523228146488/axon/js/Property.js?bust=1523235106975:269:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1523228146488/axon/js/Property.js?bust=1523235106975:216:16)
```

**Comment by pixelzoom** [comment] 2018-04-09 15:18
Duplicate of https://github.com/phetsims/blackbody-spectrum/issues/24.  Closing this issue since #24 contains more details.

**Closed by pixelzoom** 2018-04-09 15:18 UTC
Labels: type:automated-testing, type:bug

**Comment by phet-steele** [comment] 2018-04-09 15:24
Hey! 😠
